import { ProfileTypes } from '../enums';
import type { Mentor } from '../types';

export const mentors: Mentor[] = [
  {
    uuid: '0d22aa50-48ba-4ec0-96bd-aca9b54c7e2f',
    created_at: '2023-07-01',
    updated_at: '2023-07-10',
    state: 'approved',
    category: {
      category: 'Computer Science',
      uuid: 'fef68adb-e710-4d9e-8772-dc4905885088',
      created_at: '2023-10-29T14:20:04.335Z',
      updated_at: '2023-10-29T14:20:04.335Z',
    },
    application: {
      position: 'Software Engineer',
      country: 'United States',
      institution: 'Google',
      expertise: 'Web Development',
      menteeExpectations: 'Commitment and eagerness to learn',
      mentoringPhilosophy: 'Empowering mentees to reach their full potential',
      canCommit: true,
      isPastMentor: true,
      reasonToMentor: 'To give back to the community',
      cv: 'https://example.com/cv',
      linkedin: 'https://linkedin.com/',
      website: 'https://example.com',
      firstName: 'John',
      lastName: 'Doe',
      email: '',
      contactNo: '',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      noOfMentees: 0,
      category: '',
    },
    availability: true,
    profile: {
      created_at: new Date('2021-07-05T00:00:00.000Z'),
      updated_at: new Date('2021-07-06T00:00:00.000Z'),
      primary_email: 'mentor1@example.com',
      contact_email: 'mentor1@example.com',
      first_name: 'John',
      last_name: 'Doe',
      image_url: 'https://xsgames.co/randomusers/avatar.php?g=male',
      linkedin_url: 'https://linkedin.com/in/mentor1',
      type: ProfileTypes.DEFAULT,
      uuid: 'abc123',
      mentor: [],
    },
  },
  {
    uuid: '0d22aa50-48ba-4ec0-96bd-aca9b54c7e2e',
    created_at: '2023-07-02',
    updated_at: '2023-07-12',
    state: 'approved',
    category: {
      category: 'Business',
      uuid: 'fef68adb-e710-4d9e-8772-dc4905885088',
      created_at: '2023-10-29T14:20:04.335Z',
      updated_at: '2023-10-29T14:20:04.335Z',
    },
    application: {
      position: 'Chief Marketing Officer',
      country: 'Canada',
      institution: 'Facebook',
      expertise: 'Marketing',
      menteeExpectations: 'Proactive attitude and willingness to learn',
      mentoringPhilosophy: 'Sharing practical insights for professional growth',
      canCommit: true,
      isPastMentor: false,
      reasonToMentor: 'Passion for supporting aspiring entrepreneurs',
      cv: 'https://example.com/cv',
      firstName: 'Jane',
      lastName: 'Smith',
      email: '',
      contactNo: '',
      bio: '',
      noOfMentees: 0,
      category: '',
    },
    availability: true,
    profile: {
      created_at: new Date('2021-07-05T00:00:00.000Z'),
      updated_at: new Date('2021-07-06T00:00:00.000Z'),
      primary_email: 'mentor2@example.com',
      contact_email: 'mentor2@example.com',
      first_name: 'Jane',
      last_name: 'Smith',
      image_url: 'https://xsgames.co/randomusers/avatar.php?g=female',
      linkedin_url: 'https://linkedin.com/in/mentor2',
      type: ProfileTypes.DEFAULT,
      uuid: 'def456',
      mentor: [],
    },
  },
  {
    uuid: '0d22aa50-48ba-4ec0-96bd-aca9b54c7e2b',
    created_at: '2023-07-03',
    updated_at: '2023-07-12',
    state: 'approved',
    category: {
      category: 'Design',
      uuid: 'fef68acb-e710-4d9e-8772-dc4905885088',
      created_at: '2023-10-29T14:20:04.335Z',
      updated_at: '2023-10-29T14:20:04.335Z',
    },
    application: {
      position: 'UI/UX Designer',
      country: 'United Kingdom',
      expertise: 'UI/UX Design',
      institution: 'Facebook',
      menteeExpectations: 'Attention to detail and creativity',
      mentoringPhilosophy: 'Creating user-centric designs',
      canCommit: true,
      isPastMentor: true,
      reasonToMentor: 'To inspire and educate aspiring designers',
      cv: 'https://example.com/cv',
      firstName: 'Emily',
      lastName: 'Johnson',
      email: '',
      contactNo: '',
      bio: '',
      noOfMentees: 0,
      category: '',
    },
    availability: true,
    profile: {
      created_at: new Date('2021-07-05T00:00:00.000Z'),
      updated_at: new Date('2021-07-06T00:00:00.000Z'),
      primary_email: 'mentor3@example.com',
      contact_email: 'mentor3@example.com',
      first_name: 'Emily',
      last_name: 'Johnson',
      image_url: 'https://xsgames.co/randomusers/avatar.php?g=female',
      linkedin_url: 'https://linkedin.com/in/mentor3',
      type: ProfileTypes.DEFAULT,
      uuid: 'ghi789',
      mentor: [],
    },
  },
];
