import { ProfileTypes } from '../enums';
import type { Mentee, Mentor } from '../types';
import { mentors } from './mentors';

export const mentees: Mentee[] = [
  {
    uuid: 'a12aa550-48ba-4ec0-96bd-aca9b54c7e2f',
    state: 'pending',
    application: {
      firstName: 'Alice',
      lastName: 'Brown',
      email: 'alice@example.com',
      contactNo: '123-456-7890',
      cv: 'https://example.com/cv',
      isUndergrad: true,
      consentGiven: true,
      graduatedYear: undefined,
      university: 'Example University',
      yearOfStudy: 2,
      course: 'Computer Science',
      mentorId: '0d22aa50-48ba-4ec0-96bd-aca9b54c7e2f',
      submission: 'https://example.com/submission',
      company: '',
      position: '',
      profilePic: '',
    },
    mentor: mentors[0] as Mentor,
    profile: {
      created_at: new Date('2022-01-05T00:00:00.000Z'),
      updated_at: new Date('2022-01-10T00:00:00.000Z'),
      primary_email: 'mentee1@example.com',
      contact_email: 'mentee1@example.com',
      first_name: 'Alice',
      last_name: 'Brown',
      image_url: 'https://xsgames.co/randomusers/avatar.php?g=female',
      type: ProfileTypes.DEFAULT,
      uuid: 'xyz123',
      mentor: [],
    },
    created_at: new Date('2023-01-01T00:00:00.000Z'),
    updated_at: new Date('2023-01-10T00:00:00.000Z'),
    certificate_id: 'cert123',
    journal: 'Started learning JavaScript basics and building small projects.',
  },
  {
    uuid: 'b23bb660-48ba-4ec0-96bd-aca9b54c7e2e',
    state: 'pending',
    application: {
      firstName: 'Bob',
      lastName: 'Smith',
      email: 'bob@example.com',
      contactNo: '987-654-3210',
      cv: 'https://example.com/cv',
      isUndergrad: false,
      consentGiven: true,
      graduatedYear: 2020,
      university: 'Another University',
      yearOfStudy: 3,
      course: 'Marketing',
      mentorId: '0d22aa50-48ba-4ec0-96bd-aca9b54c7e2e',
      submission: 'https://example.com/submission',
      company: 'Marketing Inc',
      position: 'Assistant',
      profilePic: '',
    },
    mentor: mentors[1] as Mentor,
    profile: {
      created_at: new Date('2022-02-05T00:00:00.000Z'),
      updated_at: new Date('2022-02-10T00:00:00.000Z'),
      primary_email: 'mentee2@example.com',
      contact_email: 'mentee2@example.com',
      first_name: 'Bob',
      last_name: 'Smith',
      image_url: 'https://xsgames.co/randomusers/avatar.php?g=male',
      type: ProfileTypes.DEFAULT,
      uuid: 'uvw456',
      mentor: [],
    },
    created_at: new Date('2023-02-01T00:00:00.000Z'),
    updated_at: new Date('2023-02-10T00:00:00.000Z'),
    certificate_id: 'cert456',
    journal: 'Completed a course on marketing fundamentals and started a blog.',
  },
  {
    uuid: 'c34cc770-48ba-4ec0-96bd-aca9b54c7e2b',
    state: 'active',
    application: {
      firstName: 'Charlie',
      lastName: 'Davis',
      email: 'charlie@example.com',
      contactNo: '555-555-5555',
      cv: 'https://example.com/cv',
      isUndergrad: false,
      consentGiven: true,
      graduatedYear: 2018,
      university: 'Design School',
      yearOfStudy: 4,
      course: 'Graphic Design',
      mentorId: '0d22aa50-48ba-4ec0-96bd-aca9b54c7e2b',
      submission: 'https://example.com/submission',
      company: 'Creative Agency',
      position: 'Designer',
      profilePic: '',
    },
    mentor: mentors[0] as Mentor,
    profile: {
      created_at: new Date('2022-03-05T00:00:00.000Z'),
      updated_at: new Date('2022-03-10T00:00:00.000Z'),
      primary_email: 'mentee3@example.com',
      contact_email: 'mentee3@example.com',
      first_name: 'Charlie',
      last_name: 'Davis',
      image_url: 'https://xsgames.co/randomusers/avatar.php?g=male',
      type: ProfileTypes.DEFAULT,
      uuid: 'rst789',
      mentor: [],
    },
    created_at: new Date('2023-03-01T00:00:00.000Z'),
    updated_at: new Date('2023-03-10T00:00:00.000Z'),
    certificate_id: 'cert789',
    journal: 'Participated in design challenges and updated my portfolio.',
  },
];
